### ISSUE TITLE
"Type 'string | number | true | ArrayBuffer | BasicParameterType[] | Record<string, BasicParameterType>' must have a '[Symbol.iterator]()' method that returns an iterator." for data variable

### ISSUE THREAD

**Issue by Made1207** [lukaszkurantdev/blog-hand-landmarks#1]
It seems the plugin.call() function is returning an undefined object. I have been trying to solve this issue for almost a week now. Please help!

**Comment by lukaszkurantdev** [comment]
@Made1207 
It appears that one value passed to the MediaPipe plugin is missing. By default, Vision Camera returns frames in YUV format, but the Tensorflow that MediaPipe uses requires RGB format. 
It is therefore necessary to add the property `pixelFormat="rgb"` to the Camera component.

I've added changes to the code.
